In [70]:
# câu 1:
import pandas as pd
import numpy as np

# Mục mới

In [71]:
# câu 2 In ra màn hình 10 dòng đầu tiên
df = pd.read_csv('processed_dulieuxettuyendaihoc.csv', index_col = "STT")
df.head(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,7.8,...,7.96,8.54,7.38,K,G,K,3.184,3.416,2.952,0.0
7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,6.7,...,4.90,5.60,6.01,Y,TB,TB,1.960,2.240,2.404,1.0
8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,6.3,...,6.80,6.87,7.03,K,K,K,2.720,2.748,2.812,0.0
9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,6.8,...,6.23,6.72,7.56,TB,K,K,2.492,2.688,3.024,0.0
10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,6.8,...,6.80,7.25,7.03,K,K,K,2.720,2.900,2.812,0.0

In [72]:
# câu 3 In ra 10 dong cuoi cung
df.tail(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,8.3,...,7.84,8.27,8.29,K,G,G,3.136,3.308,3.316,1.0
92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,6.9,...,6.17,6.63,7.65,TB,K,K,2.468,2.652,3.060,0.0
93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,6.1,...,6.10,6.53,6.76,TB,K,K,2.440,2.612,2.704,0.0
94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,5.8,...,6.53,7.12,6.97,K,K,K,2.612,2.848,2.788,0.0
95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,7.2,...,6.10,6.71,6.68,TB,K,K,2.440,2.684,2.672,0.0
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

In [73]:
# câu 4:Thống kê dữ liệu thiếu cho cột dân tộc và hiệu chỉnh dữ liệu thiếu như sau: Mặc định thiếu thì điền giá trị 0.
df['DT'] = df['DT'].fillna(0)
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

In [74]:
# câu 5: Thống kê dữ liệu thiếu cho biến T1 và hiệu chỉnh dữ liệu, lưu ý việc thay thế dữ liệu thiếu sử dụng phương pháp Mean.
df['T1'] = df['T1'].fillna(df['T1'].mean())
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

In [78]:
# câu 6: Thực hiện xử lý lần lượt tất cả dữ liệu thiếu cho các biến về điểm số còn lại
cac_cot_diem = ['T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1',
                'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2',
                'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6',
                'DH1', 'DH2', 'DH3']

for col in cac_cot_diem:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].mean())
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

In [81]:
# câu 7: Tạo các biến TBM1, TBM2, TBM3 tương ứng với trung bình môn của các năm lớp 10, 11 và
12.
# • Công thức tính: TBM = (T*2 + L + H + S + V*2 + X + D + N) / 10
df['TBM1'] = (df['T1']*2 + df['L1'] + df['H1'] + df['S1'] + df['V1']*2 + df['X1'] + df['D1'] + df['N1']) / 10
df['TBM2'] = (df['T2']*2 + df['L2'] + df['H2'] + df['S2'] + df['V2']*2 + df['X2'] + df['D2'] + df['N2']) / 10
df['TBM3'] = (df['T6']*2 + df['L6'] + df['H6'] + df['S6'] + df['V6']*2 + df['X6'] + df['D6'] + df['N6']) / 10
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

In [86]:
# câu 8: Tạo các biến xếp loại XL1, XL2 và XL3 dựa trên TBM1,TBM2 và TBM3 cho từng năm lớp 10, 11, 12 như sau:
# • Nhỏ hơn 5.0 xếp loại: yếu (kí hiệu là Y)
# • Từ 5.0 đến dưới 6.5: trung bình (kí hiệu là TB)
# • Từ 6.5 đến dưới 8.0: khá (kí hiệu là K)
# • Từ 8.0 đến dưới 9.0: giỏi (kí hiệu là G)
# • Từ 9.0 trở lên: xuất sắc (kí hiệu là XS)
def xeploai(x):
  if x < 5: return 'Y'
  elif x < 6.5: return 'TB'
  elif x < 8: return 'K'
  elif x < 9: return 'G'
  else: return "XS"
df['XL1'] = df['TBM1'].apply(xeploai)
df['XL2'] = df['TBM2'].apply(xeploai)
df['XL3'] = df['TBM3'].apply(xeploai)
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

In [87]:
# câu 9: Tạo các biến US_TBM1, US_TBM2 và US_TBM3 để chuyển điểm trung bình các năm lớp 10, 11 và 12 từ thang điểm 10 của Việt Nam sang thang điểm 4 của Mỹ. Sử dụng phương pháp Min-Max Normalization
df['US_TBM1'] = df['TBM1'] / 10 * 4
df['US_TBM2'] = df['TBM2'] / 10 * 4
df['US_TBM3'] = df['TBM3'] / 10 * 4
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0.0
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0.0
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1.0
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0.0
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,7.43,7.42,6.83,K,K,K,2.972,2.968,2.732,0.0
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,4.93,5.15,6.39,Y,TB,TB,1.972,2.060,2.556,0.0
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.05,7.84,7.67,K,K,K,2.820,3.136,3.068,1.0
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,4.15,4.72,5.29,Y,Y,TB,1.660,1.888,2.116,0.0
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.26,5.72,5.85,TB,TB,TB,2.104,2.288,2.340,0.0

In [92]:
# câu 10: Tạo biến kết quả xét tuyển (kí hiệu là KQXT) nhằm xác định sinh viên đậu (giá trị "1") và rớt (giá trị "0") vào các khối dựa trên điểm DH1, DH2 và DH3 như sau
# • Với khối A, A1 nếu [(DH1*2 + DH2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt
# • Với khối B nếu [(DH1 + DH2*2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt
# • Với khối khác nếu [(DH1 + DH2 + DH3)/3] lớn hơn hoặc bằng 5.0 thì đậu, ngược lại là rớt
# Câu 10: Hàm tính điểm và xét tuyển (1: Đậu, 0: Rớt)
def tinh_kqxt(row):
    khoi = str(row['KT']).strip()
    # Tính điểm tổng kết dựa theo khối thi
    diem = (row['DH1']*2 + row['DH2'] + row['DH3'])/4 if khoi in ['A', 'A1'] else \
           (row['DH1'] + row['DH2']*2 + row['DH3'])/4 if khoi == 'B' else \
           (row['DH1'] + row['DH2'] + row['DH3'])/3
    return 1 if diem >= 5.0 else 0

df['KQXT'] = df.apply(tinh_kqxt, axis=1)
df.head(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,KQXT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,7.00,7.54,7.01,K,K,K,2.800,3.016,2.804,0
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,4.69,5.47,5.07,Y,TB,TB,1.876,2.188,2.028,0
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.77,5.38,6.04,TB,TB,TB,2.308,2.152,2.416,1
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,6.21,5.20,6.88,TB,TB,K,2.484,2.080,2.752,0
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.50,6.36,6.99,K,TB,K,2.600,2.544,2.796,0
6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,7.8,...,7.96,8.54,7.38,K,G,K,3.184,3.416,2.952,0
7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,6.7,...,4.90,5.60,6.01,Y,TB,TB,1.960,2.240,2.404,1
8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,6.3,...,6.80,6.87,7.03,K,K,K,2.720,2.748,2.812,0
9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,6.8,...,6.23,6.72,7.56,TB,K,K,2.492,2.688,3.024,0
10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,6.8,...,6.80,7.25,7.03,K,K,K,2.720,2.900,2.812,0